force-app/main/default/objects/SetupAuditTrail2__c/SetupAuditTrail2__c.object-meta.xml
<CustomObject>
    <description>The purpose of this custom object is to function as a persistent clone of the standard SetupAuditTrail entity.</description>
    <label>Setup Audit Trail 2</label>
    <nameField>
        <displayFormat>SAT2-{0000000}</displayFormat>
        <label>SAT2 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Audit Trails 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SetupAuditTrail2__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The category of the change made in Setup. For example, a value of PermSetCreate indicates that an administrator created a permission set. The Display field contains more specific information.</description>
    <label>Action</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SetupAuditTrail2__c/fields/Display__c.field-meta.xml
<CustomField>
    <fullName>Display__c</fullName>
    <description>The full description of changes made in Setup. For example, if the Action field has a value of PermSetCreate, the Display field has a value like “Created permission set MAD: with user license Salesforce.</description>
    <label>Display</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SetupAuditTrail2__c/fields/SetupAuditTrailCreatedByName__c.field-meta.xml
<CustomField>
    <fullName>SetupAuditTrailCreatedByName__c</fullName>
    <label>Setup Audit Trail Created By Name</label>
    <length>121</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SetupAuditTrail2__c/fields/SetupAuditTrailRecordCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>SetupAuditTrailRecordCreatedDate__c</fullName>
    <description>Represents the source record create date from the SetupAuditTrail object.</description>
    <label>Setup Audit Trail Record Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SetupAuditTrail2__c/fields/SetupAuditTrailRecordId__c.field-meta.xml
<CustomField>
    <fullName>SetupAuditTrailRecordId__c</fullName>
    <description>Represents the source record Id from the SetupAuditTrail object.</description>
    <label>Setup Audit Trail Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SetupAuditTrail2Last24Hours_Batch.cls
public with sharing class SetupAuditTrail2Last24Hours_Batch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext batchContext) {
        DateTime now = DateTime.now();
        DateTime priorTwentyFourHours = now.addHours(-24);
        String setupAuditTrailQuery = 'SELECT Id, Action, Display, CreatedBy.Name, CreatedDate FROM SetupAuditTrail ' +
                       'WHERE CreatedDate >= :priorTwentyFourHours AND CreatedDate < :now';
        if(Test.isRunningTest()) {
        	setupAuditTrailQuery += ' LIMIT 200';
    	}
        return Database.getQueryLocator(setupAuditTrailQuery);
    }

    public void execute(Database.BatchableContext batchContext, List<SetupAuditTrail> records) {
        String defaultCreatedByName = Label.SetupAuditTrail2_SfdcString;

        Map<Id, SetupAuditTrail> recordMap = new Map<Id, SetupAuditTrail>();
        for (SetupAuditTrail record : records) {
            recordMap.put(record.Id, record);
        }

        List<SetupAuditTrail2__c> existingRecords = [SELECT SetupAuditTrailRecordId__c FROM SetupAuditTrail2__c WHERE SetupAuditTrailRecordId__c IN :recordMap.keySet()];

        for (SetupAuditTrail2__c existingRecord : existingRecords) {
            recordMap.remove(existingRecord.SetupAuditTrailRecordId__c);
        }

        List<SetupAuditTrail2__c> newRecords = new List<SetupAuditTrail2__c>();
        for (SetupAuditTrail record : recordMap.values()) {
            String createdByName = String.isBlank(record.CreatedBy.Name) ? defaultCreatedByName : record.CreatedBy.Name;
            SetupAuditTrail2__c newRecord = new SetupAuditTrail2__c(
                SetupAuditTrailRecordId__c          = record.Id,
                Action__c                           = record.Action,
                Display__c                          = record.Display,
                SetupAuditTrailCreatedByName__c     = createdByName,
                SetupAuditTrailRecordCreatedDate__c = record.CreatedDate
            );
            newRecords.add(newRecord);
        }

        if (!newRecords.isEmpty()) {
            Database.SaveResult[] results = Database.insert(newRecords, false);
            logErrors(results);
        }
    }

    public void finish(Database.BatchableContext batchContext) {
        System.debug('Batch process completed. Processed ' + batchContext.getJobId());
    }

    private void logErrors(Database.SaveResult[] results) {
        List<String> errorMessages = new List<String>();
        for (Database.SaveResult result : results) {
            if (!result.isSuccess()) {
                for (Database.Error error : result.getErrors()) {
                    errorMessages.add('Error inserting record: ' + error.getMessage());
                }
            }
        }
        if (!errorMessages.isEmpty()) {
            System.debug('Errors: ' + String.join(errorMessages, '\n'));
        }
    }
}